version: "3.9"

services:
  backend:
    image: kennethreitz/httpbin
    restart: unless-stopped

  opa:
    image: openpolicyagent/opa:latest-envoy
    command:
      - run
      - --server
      - --addr=localhost:8181
      - --diagnostic-addr=0.0.0.0:8282
      - --config-file=/config/config.yaml
      - /policy
      - /data
    volumes:
      - ./opa/config.yaml:/config/config.yaml:ro
      - ./opa/policy.rego:/policy/policy.rego:ro
      - ./opa/data:/data:ro
    restart: unless-stopped
    expose:
      - "9191" # gRPC ext_authz плагина

  envoy:
    image: envoyproxy/envoy:v1.30-latest
    depends_on: [opa, backend]
    volumes:
      - ./envoy/envoy.yaml:/etc/envoy/envoy.yaml:ro
    ports:
      - "8000:8000" # входной порт
      - "9901:9901" # admin Envoy
    restart: unless-stopped
