plugins:
  envoy_ext_authz_grpc:
    addr: :9191
    path: envoy/authz/result       # => data.envoy.authz.result
    skip_request_body_parse: false # чтобы появился input.parsed_body
    enable_reflection: false

decision_logs:
  console: true
